### ISSUE TITLE
Господи помилуй...

### ISSUE THREAD

**Issue by AlphaBeth** [victor-livshits/web3#1]
https://github.com/victor-livshits/web3/blob/4d48451667c89d0c0d302f9cf944eb5698463543/src/main/java/com/example/lab3/Models/NodeDAO.java#L16-L22

Использовать подходящие инструменты для запросов с параметрами, а не конкатенировать строчку с ними.

**Comment by victor-livshits** [comment]
Господь помиловал! Отныне строки не конкатинируются.

Не уверен, что нужно писать сюда в ответ, что я поправил, однако я всё равно это сделаю, потому что это забавно (раз), вы с этого проиграете в голос (два), мне нравится (три)

Ссылка на топовый фикс конкатинации строк.
https://github.com/victor-livshits/web3/commit/8115166e4417641d215ddb903d23c4d58fe8a961#diff-75953ba55641e9b0336076d749fdbc1d93c5e9f8e5e8f396541a4061af7b038f
