### ISSUE TITLE
sequence в БД

### ISSUE THREAD

**Issue by AlphaBeth** [victor-livshits/web3#4]
https://github.com/victor-livshits/web3/blob/4d48451667c89d0c0d302f9cf944eb5698463543/src/main/java/com/example/lab3/Models/Node.java#L18

**Comment by victor-livshits** [comment]
Теперь в общем юзаю serial в бд, работает с кайфом. Клёвая штука кстати, спасибо, не знал))) 
всегда мечтал в 4 утра переделывать каркас базы ыыыыыыыыыыы ыыыыыыыы ыыыыыыы
если вдруг вы это будете читать, то послушайте клёвую песню
Nouvelle Vague - In a Manner of Speaking
