### ISSUE TITLE
Картинка отображает все точки

### ISSUE THREAD

**Issue by AlphaBeth** [victor-livshits/web3#7]

**Comment by victor-livshits** [comment]
@AlphaBeth 

Когда-нибудь я узнаю про пул-реквесты и то, как это все по уму оформлять, ну а пока что вот. 
Еще интересно, приходит ли вам письмо на почту с каждым закрытым ишью, или я один получил 10-ку писем за раз.

Ссылка на топовый коммит, в котором кроме всего прочего код стал чуть меньше пахнуть(функции стали поменьше, скинули ответсвенность)
https://github.com/victor-livshits/web3/commit/2d4b96bacc1a651258aa009c21f7bf9175fbffbc
